

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformValidate
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
        - task: PublishPipelineArtifact@1
          displayName: Publish Artifacts
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            artifact: 'terraform-manifests-out'
            publishLocation: 'pipeline'

        - task: TerraformInstaller@0
          displayName: Terraform Install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            backendType: 'azurerm'
            backendServiceArm: 'terraform-aks-azurerm-svc-con'
            backendAzureRmSubscriptionId: 'ddb8958b-0d44-46bf-bdaa-46c88bd07cf0'
            ensureBackend: true
            backendAzureRmResourceGroupName: 'terraform-storage-rg'
            backendAzureRmResourceGroupLocation: 'westus'
            backendAzureRmStorageAccountName: 'statekubernetesfiles'
            backendAzureRmContainerName: 'terraformstatecontainer22'
            backendAzureRmKey: 'aks-base.tfstate'
            allowTelemetryCollection: true

        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            allowTelemetryCollection: false